development:
  secret_key_base: 99529d4e743554e0578b32911755a063e21464a138d2f8c34709a39e123620721be7bc9060515138b706db913bc4883d45afe5603fd3252843a11ec9dee898e0
  auth0_client_id: <%= ENV["AUTH0_CLIENT_ID"] %>
  auth0_client_secret: <%= ENV["AUTH0_CLIENT_SECRET"] %>
  bugsnag_api_key: <% ENV["BUGSNAG_API_KEY"] %>
  web_app_url: http://localhost:3001

test:
  secret_key_base: 8a9c705d3b0320158e1d8f8b3414c2d68ad6538da5c2989c017682d96b583e0c1955746ee4d15e388216b38d37b53c2a408de29148f57ee1d57d59f0dd925427
  auth0_client_id: test
  auth0_client_secret: test

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  auth0_client_id: <%= ENV["AUTH0_CLIENT_ID"] %>
  auth0_client_secret: <%= ENV["AUTH0_CLIENT_SECRET"] %>
  bugsnag_api_key: <% ENV["BUGSNAG_API_KEY"] %>
  aws_host_name: <% ENV["AWS_HOST_NAME"] %>
  s3_bucket_name: <% ENV["S3_BUCKET_NAME"] %>
  aws_access_key_id: <% ENV["AWS_ACCESS_KEY_ID"] %>
  asw_secret_access_key: <% ENV["AWS_SECRET_ACCESS_KEY"] %>
  aws_region: <% ENV["AWS_REGION"] %>
  cloudfront_url: <% ENV["CLOUDFRONT_URL"] %>
  web_app_url: https://www.giddy.bike
